### ISSUE TITLE
Doc/Commentaire: corrections à faire pour la classe Singleton

### ISSUE THREAD

**Issue by gmaillet** [IGNF/Borea#130]
- dor/for en ligne 2
- espace manquant en ligne 8
- cette classe n'est pas uniquement utilisée pour les DTM, mais aussi pour la classe ProjEngine

éventuellement rappeler qu'il s'agit de l'implémentation d'un des "Design Pattern" classique

**Comment by ACornuIGN** [comment]
#131
Corrections effectuées
